import { useMutation } from '@tanstack/react-query';
import * as queryKeys from 'src/constants/queryKeys';
import {
  LocalCreatePayload,
  UsersPermissionsUserRegistration,
  LocalRegisterCreatePayload,
  Error,
} from 'src/types/api-autogenerated';
import { postSignIn, postRegisterUser } from '../auth';

export const useSignInMutation = () => {
  return useMutation<
    Required<UsersPermissionsUserRegistration>,
    Error,
    Required<LocalCreatePayload>
  >({
    mutationKey: [queryKeys.POST_SIGN_IN],
    mutationFn: ({ identifier, password }) =>
      postSignIn({ email: identifier, password }),
  });
};

export const useSignUpMutation = () => {
  return useMutation<
    Required<UsersPermissionsUserRegistration>,
    Error,
    Required<LocalRegisterCreatePayload>
  >({
    mutationKey: [queryKeys.POST_SIGN_UP],
    mutationFn: (inputs) => postRegisterUser(inputs),
  });
};
