import { useQuery, UseQueryResult } from '@tanstack/react-query';
import * as queryKeys from 'src/constants/queryKeys';
import { requestUserWorkouts } from 'src/requests/request-workouts';
import { UserWorkoutListResponse } from 'src/types/api-autogenerated';

export const useGetUserWorkouts =
  (): UseQueryResult<UserWorkoutListResponse> => {
    return useQuery({
      queryKey: [queryKeys.GET_WORKOUTS],
      queryFn: () => requestUserWorkouts() as Promise<UserWorkoutListResponse>,
    });
  };
