import { useQuery, UseQueryResult } from '@tanstack/react-query';
import * as queryKeys from 'src/constants/queryKeys';
import { requestUserWorkouts } from 'src/requests/workouts';
import { CoucheWorkoutListResponse } from 'src/types/api-autogenerated';

export const useGetUserWorkouts =
  (): UseQueryResult<CoucheWorkoutListResponse> => {
    return useQuery({
      queryKey: [queryKeys.GET_WORKOUTS],
      queryFn: () =>
        requestUserWorkouts() as Promise<CoucheWorkoutListResponse>,
    });
  };
