import { Workout, UserWorkout, Exercise } from 'src/types/api-autogenerated';

export type WorkoutListItemProps = {
  workout: UserWorkout & { workout: Workout & { exercises: Exercise[] } };
  onPress: (workoutId: string) => void;
};
