export const GET_WORKOUTS = 'GET_WORKOUTS';
export const GET_USER_WORKOUT = 'GET_USER_WORKOUT';
export const POST_COMPLETE_WORKOUT = 'POST_COMPLETE_WORKOUT';

export const GET_CURRENT_EXERCISE = 'GET_CURRENT_EXERCISE';
