export const GET_WORKOUTS = 'GET_WORKOUTS';
export const GET_WORKOUT = 'GET_WORKOUT';
export const GET_AVAILABLE_WORKOUTS = 'GET_AVAILABLE_WORKOUTS';
export const GET_USER_WORKOUT = 'GET_USER_WORKOUT';
export const POST_COMPLETE_WORKOUT = 'POST_COMPLETE_WORKOUT';

export const GET_CURRENT_EXERCISE = 'GET_CURRENT_EXERCISE';

export const POST_SIGN_IN = 'POST_SIGN_IN';
export const POST_SIGN_UP = 'POST_SIGN_UP';
