import { Exercise, Workout, UserWorkout } from 'src/types/api-autogenerated';
import { WorkoutStackScreenProps } from 'src/types/navigation.d';
import { WorkoutStack } from 'src/constants/navigation';

export type WorkoutScreenProps =
  {} & WorkoutStackScreenProps<WorkoutStack.WorkoutScreen>;

export type WorkoutScreenState = {
  selectedWorkout:
    | (UserWorkout & { workout: Workout & { exercises: Exercise[] } })
    | null;
  currentExerciseId: string;
  workoutInProgress: boolean;
  workoutCompleted: boolean;
  workoutScore: number;
  exercises: Exercise[];
};
