import { API } from 'src/constants/settings';
import { LocalRegisterCreatePayload } from 'src/types/api-autogenerated';

export const postSignIn = async ({
  email,
  password,
}: Omit<Required<LocalRegisterCreatePayload>, 'username'>) => {
  const response = await fetch(new URL(`${API}/auth/local`), {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ identifier: email, password }),
  });

  if (!response.ok) {
    throw new Error('Sign in failed');
  }

  return response.json();
};

export const postRegisterUser = async (
  input: Required<LocalRegisterCreatePayload>,
) => {
  const response = await fetch(new URL(`${API}/auth/local/register`), {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(input),
  });

  if (!response.ok) {
    throw new Error('Sign up failed');
  }

  return response.json();
};
