import { Workout, CoucheWorkout, Exercise } from 'src/types/api-autogenerated';

export type GetUserWorkout = {
  data: CoucheWorkout & { workout: Workout & { exercises: Exercise[] } };
};

export type GetUserWorkouts = {
  data: GetUserWorkout['data'][];
};

export type GetExerciseResponse = {
  data: Exercise;
};
