import React from 'react';
import { useTranslation } from 'react-i18next';
import { FeedCard } from 'src/components/FeedCard';
import { CardHeader } from 'src/components/CardHeader';
import { WorkoutListItem } from '../WorkoutListItem';
import { UserWorkout, Workout, Exercise } from 'src/types/api-autogenerated';

interface UpcomingWorkoutsFeedProps {
  workouts: (UserWorkout & { workout: Workout & { exercises: Exercise[] } })[];
}

export const UpcomingWorkoutsFeed: React.FC<UpcomingWorkoutsFeedProps> = ({
  workouts,
}) => {
  const { t } = useTranslation();
  const handleViewAllWorkouts = () => {
    // Navigate to all workouts screen
    console.log('Navigate to all workouts');
  };

  const handleWorkoutPress = (workoutId: string) => {
    // Navigate to workout details
    console.log('Navigate to workout details:', workoutId);
  };

  return (
    <FeedCard>
      <CardHeader
        title={t('upcoming-workouts-card--title')}
        actionText={t('upcoming-workouts-card--action-text')}
        onAction={handleViewAllWorkouts}
      />

      {workouts.map((workout) => (
        <WorkoutListItem
          key={workout.documentId}
          workout={workout}
          onPress={handleWorkoutPress}
        />
      ))}
    </FeedCard>
  );
};
