import { Exercise } from 'src/types';

export const mockExercises: Exercise[] = [
  // Chest
  {
    id: '1',
    name: 'Bench Press',
    category: 'Chest',
    equipment: 'Barbell',
    sets: 4,
    reps: 8,
    completed: false,
  },
  {
    id: '2',
    name: 'Incline Bench Press',
    category: 'Chest',
    equipment: 'Barbell',
    sets: 4,
    reps: 8,
    completed: false,
  },
  {
    id: '3',
    name: 'Chest Fly',
    category: 'Chest',
    equipment: 'Dumbbell',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '4',
    name: 'Push-up',
    category: 'Chest',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 15,
    completed: false,
  },
  {
    id: '5',
    name: 'Cable Crossover',
    category: 'Chest',
    equipment: 'Cable',
    sets: 3,
    reps: 12,
    completed: false,
  },

  // Back
  {
    id: '6',
    name: 'Deadlift',
    category: 'Back',
    equipment: 'Barbell',
    sets: 4,
    reps: 6,
    completed: false,
  },
  {
    id: '7',
    name: 'Pull-up',
    category: 'Back',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 10,
    completed: false,
  },
  {
    id: '8',
    name: 'Bent Over Row',
    category: 'Back',
    equipment: 'Barbell',
    sets: 4,
    reps: 8,
    completed: false,
  },
  {
    id: '9',
    name: 'Lat Pulldown',
    category: 'Back',
    equipment: 'Cable',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '10',
    name: 'Seated Row',
    category: 'Back',
    equipment: 'Cable',
    sets: 3,
    reps: 12,
    completed: false,
  },

  // Legs
  {
    id: '11',
    name: 'Squat',
    category: 'Legs',
    equipment: 'Barbell',
    sets: 4,
    reps: 10,
    completed: false,
  },
  {
    id: '12',
    name: 'Leg Press',
    category: 'Legs',
    equipment: 'Machine',
    sets: 4,
    reps: 12,
    completed: false,
  },
  {
    id: '13',
    name: 'Leg Extension',
    category: 'Legs',
    equipment: 'Machine',
    sets: 3,
    reps: 15,
    completed: false,
  },
  {
    id: '14',
    name: 'Leg Curl',
    category: 'Legs',
    equipment: 'Machine',
    sets: 3,
    reps: 15,
    completed: false,
  },
  {
    id: '15',
    name: 'Calf Raise',
    category: 'Legs',
    equipment: 'Machine',
    sets: 4,
    reps: 20,
    completed: false,
  },

  // Shoulders
  {
    id: '16',
    name: 'Overhead Press',
    category: 'Shoulders',
    equipment: 'Barbell',
    sets: 4,
    reps: 8,
    completed: false,
  },
  {
    id: '17',
    name: 'Lateral Raise',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '18',
    name: 'Front Raise',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '19',
    name: 'Face Pull',
    category: 'Shoulders',
    equipment: 'Cable',
    sets: 3,
    reps: 15,
    completed: false,
  },
  {
    id: '20',
    name: 'Shrug',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    sets: 4,
    reps: 12,
    completed: false,
  },

  // Arms
  {
    id: '21',
    name: 'Bicep Curl',
    category: 'Arms',
    equipment: 'Dumbbell',
    sets: 4,
    reps: 10,
    completed: false,
  },
  {
    id: '22',
    name: 'Tricep Extension',
    category: 'Arms',
    equipment: 'Cable',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '23',
    name: 'Hammer Curl',
    category: 'Arms',
    equipment: 'Dumbbell',
    sets: 4,
    reps: 10,
    completed: false,
  },
  {
    id: '24',
    name: 'Skull Crusher',
    category: 'Arms',
    equipment: 'Barbell',
    sets: 3,
    reps: 12,
    completed: false,
  },
  {
    id: '25',
    name: 'Preacher Curl',
    category: 'Arms',
    equipment: 'Barbell',
    sets: 3,
    reps: 12,
    completed: false,
  },

  // Core
  {
    id: '26',
    name: 'Plank',
    category: 'Core',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 60,
    completed: false,
  },
  {
    id: '27',
    name: 'Crunch',
    category: 'Core',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 20,
    completed: false,
  },
  {
    id: '28',
    name: 'Russian Twist',
    category: 'Core',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 20,
    completed: false,
  },
  {
    id: '29',
    name: 'Leg Raise',
    category: 'Core',
    equipment: 'Bodyweight',
    sets: 3,
    reps: 15,
    completed: false,
  },
  {
    id: '30',
    name: 'Ab Wheel Rollout',
    category: 'Core',
    equipment: 'Ab Wheel',
    sets: 3,
    reps: 12,
    completed: false,
  },
];

export const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];
